# api/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  ##### Uncomment for Docker
  ##### Prefer DATABASE_URL if present (e.g., in Docker)
  # url: <%= ENV["DATABASE_URL"] %>
  # host: <%= ENV.fetch("DB_HOST", nil) || "::1" %>   # use "::1" for your setup; set nil to use socket
  # port: <%= ENV.fetch("DB_PORT", 5432) %>
  # username: <%= ENV.fetch("POSTGRES_USER", "mehul") %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>         # likely blank locally
development:
  <<: *default
  database: api_development
  # If DATABASE_URL is NOT set, these fields apply:

  ##### Uncomment for Docker

  


test:
  <<: *default
  database: api_test


production:
  <<: *default
  database: api_production
  # In prod you'll usually use DATABASE_URL. If not:
  # host: <%= ENV["DB_HOST"] %>
  # port: <%= ENV.fetch("DB_PORT", 5432) %>
  # username: <%= ENV["POSTGRES_USER"] %>
  # password: <%= ENV["API_DATABASE_PASSWORD"] %>
